server:
  port: 8082
  shutdown: graceful
  max-http-request-header-size: 2MB

spring:
  profiles:
    active: dev
  application:
    name: event-service
  lifecycle:
    timeout-per-shutdown-phase: "120s"

springdoc:
  paths-to-exclude: /swagger-resources/**, /v3/api-docs/**, /v2/api-docs/**
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
