spring:
  application:
    name: event-service
    profiles:
      active: dev

  lifecycle:
    timeout-per-shutdown-phase: "90s"

server:
  port: 8082
  shutdown: graceful
  max-http-request-header-size: 2MB


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

springdoc:
  paths-to-exclude: /swagger-resources/**, /v3/api-docs/**, /v2/api-docs/**
